
name: Client3 - Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "prod","uat" ]

env:
  APP_LOCATION: "/"
  APP_ARTIFACT_LOCATION: "dist" # location of client code build output

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: "${{github.ref_name}}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo VITE_LOGIN_APP_URL=$(az keyvault secret show --vault-name Client3${{github.ref_name}}-centralus --name VITE-LOGIN-APP-URL --query value -o tsv) >> $GITHUB_ENV
            echo VITE_API_URL=$(az keyvault secret show --vault-name Client3${{github.ref_name}}-centralus --name VITE-API-URL --query value -o tsv) >> $GITHUB_ENV
            echo VITE_RUNTIME_CONFIG_URL=$(az keyvault secret show --vault-name Client3${{github.ref_name}}-centralus --name VITE-RUNTIME-CONFIG-URL --query value -o tsv) >> $GITHUB_ENV
            echo VITE_APP_TENANT_ID=$(az keyvault secret show --vault-name Client3${{github.ref_name}}-centralus --name VITE-APP-TENANT-ID --query value -o tsv) >> $GITHUB_ENV

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
        env:
          VITE_LOGIN_APP_URL: ${{ env.VITE_LOGIN_APP_URL }}
          VITE_API_URL: ${{ env.VITE_API_URL }}
          VITE_RUNTIME_CONFIG_URL: ${{ env.VITE_RUNTIME_CONFIG_URL }}
          VITE_APP_TENANT_ID: ${{ env.VITE_APP_TENANT_ID }}
